[tool.poetry]
name = "nonebot-plugin-mediawiki"
version = "0.1.2"
description = "nonebot2 mediawiki 查询插件"
authors = ["KoishiChan <68314080+KoishiStudio@users.noreply.github.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/KoishiStudio/nonebot-plugin-mediawiki"

[tool.poetry.dependencies]
python = ">=3.8"
aiohttp = "~=3.8.1"
nonebot2 = "~=2.0.0b2"
nonebot-adapter-onebot = "~=2.0.0b1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
